# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:20
from __future__ import unicode_literals

import closuredag.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('node_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'nodes',
            },
            bases=(models.Model, closuredag.models.VertexBase),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_rel', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeOne',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dag.Node')),
                ('value_one', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'nodes one',
                'verbose_name': 'node one',
            },
            bases=('dag.node',),
        ),
        migrations.CreateModel(
            name='NodeTwo',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dag.Node')),
                ('value_two', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'nodes two',
                'verbose_name': 'node two',
            },
            bases=('dag.node',),
        ),
        migrations.AddField(
            model_name='relation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Node_parent', to='dag.Node'),
        ),
        migrations.AddField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Node_child', to='dag.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_parents', through='dag.Relation', to='dag.Node'),
        ),
    ]
