# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0002_remove_node_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Node_p', to='dag.Node')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Node_c', to='dag.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
