# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0004_remove_closure_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closure',
            name='child',
        ),
        migrations.RemoveField(
            model_name='closure',
            name='parent',
        ),
        migrations.AddField(
            model_name='closure',
            name='directEdge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Node_direct', to='dag.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closure',
            name='end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Relation_end', to='dag.Relation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closure',
            name='entryEdge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Node_entry', to='dag.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closure',
            name='exitEdge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Node_exit', to='dag.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closure',
            name='hops',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closure',
            name='start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Relation_start', to='dag.Relation'),
            preserve_default=False,
        ),
    ]
