# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0005_auto_20180220_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closure',
            old_name='directEdge',
            new_name='direct_edge',
        ),
        migrations.RenameField(
            model_name='closure',
            old_name='entryEdge',
            new_name='entry_edge',
        ),
        migrations.RenameField(
            model_name='closure',
            old_name='exitEdge',
            new_name='exit_edge',
        ),
    ]
