# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0006_auto_20180220_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closure',
            old_name='end',
            new_name='end_vertex',
        ),
        migrations.RenameField(
            model_name='closure',
            old_name='start',
            new_name='start_vertex',
        ),
    ]
