# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0007_auto_20180220_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closure',
            name='direct_edge',
        ),
        migrations.RemoveField(
            model_name='closure',
            name='end_vertex',
        ),
        migrations.RemoveField(
            model_name='closure',
            name='entry_edge',
        ),
        migrations.RemoveField(
            model_name='closure',
            name='exit_edge',
        ),
        migrations.RemoveField(
            model_name='closure',
            name='start_vertex',
        ),
        migrations.AddField(
            model_name='relation',
            name='direct_edge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_direct', to='dag.Relation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='entry_edge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_entry', to='dag.Relation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='exit_edge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='dag.Relation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='hops',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Closure',
        ),
    ]
