# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0008_auto_20180220_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='direct_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_direct', to='dag.Relation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='entry_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_entry', to='dag.Relation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='exit_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='dag.Relation'),
        ),
    ]
