# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0009_auto_20180220_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='direct_edge',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='entry_edge',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='exit_edge',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='hops',
        ),
    ]
