# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0010_auto_20180220_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='direct_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directs_edges', to='dag.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='entry_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries_edges', to='dag.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='exit_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exits_edges', to='dag.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='hops',
            field=models.IntegerField(default=0),
        ),
    ]
