# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0012_auto_20180221_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='direct_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directs_edges', to='dag.Relation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='entry_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries_edges', to='dag.Relation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='exit_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exits_edges', to='dag.Relation'),
        ),
    ]
