# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0013_auto_20180221_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='etype',
            field=models.CharField(default='direct', max_length=20),
        ),
    ]
