# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0014_relation_etype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', through='dag.Relation', to='dag.Node'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='direct_edge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='entry_edge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='exit_edge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='value_rel',
            field=models.FloatField(default=99),
        ),
    ]
