# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0015_auto_20180222_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='direct_edge',
            new_name='direct_edge_id',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='entry_edge',
            new_name='entry_edge_id',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='exit_edge',
            new_name='exit_edge_id',
        ),
    ]
