# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0016_auto_20180222_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeone',
            name='value_one',
            field=models.CharField(default=99, max_length=32),
        ),
        migrations.AlterField(
            model_name='nodetwo',
            name='value_two',
            field=models.CharField(default=99, max_length=32),
        ),
        migrations.AlterField(
            model_name='relation',
            name='value_rel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
